# pihole-dns - Ansible playbooks to configure a recursive PiHole DNS server
# Copyright (C) 2022  Charles German <5donuts@pm.me>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
- name: Copy over the DHCP config
  become: yes
  ansible.builtin.template:
    src: templates/04-pihole-static-dhcp.conf.j2
    dest: "{{ pihole_static_dhcp_path }}"
    mode: '0644' # rw-r--r--
  when: (dhcp.enabled is defined) and dhcp.enabled

- name: Mark PiHole DHCP to be configured
  ansible.builtin.set_fact:
    configure_pihole_dhcp: yes
    cacheable: yes
  when: (dhcp.enabled is defined) and dhcp.enabled
